_target_: navsim.agents.recogdrive.recogdrive_agent.ReCogDriveAgent
_convert_: 'all'

trajectory_sampling:
  _target_: nuplan.planning.simulation.trajectory.trajectory_sampling.TrajectorySampling
  _convert_: 'all'
  time_horizon: 4
  interval_length: 0.5
checkpoint_path: ''
vlm_path: ''
cam_type: 'single'
vlm_type: 'internvl'
dit_type: 'small'
sampling_method: 'ddim'
cache_mode: False
cache_hidden_state: True
metric_cache_path: ''
reference_policy_checkpoint: ''
vlm_size: 'small'
train_backbone: false
vlm_prune_keep_ratio: 1.0
vlm_prune_method: 'tfps'
diffusion_num_inference_steps: 5
image_max_num: 12
image_backend: 'pil'
dit_pointwise_variant: 'baseline'
fast_ddim_action: false
prompt_variant: 'full'
grpo: False
lr: 1e-4
